export enum DesignCodeSuffixPattern {
  LETTER_SUFFIX = 'LETTER_SUFFIX',
  LETTER_SUFFIX_DASH = 'LETTER_SUFFIX_DASH',
  NUMERIC_SUFFIX = 'NUMERIC_SUFFIX',
  NUMERIC_SUFFIX_DASH = 'NUMERIC_SUFFIX_DASH',
}
