export enum DesignCodeSapSegmentName {
  FASE = 'FASE',
  POTENCIA = 'POTENCIA',
  TENSION_PRIMARIA = 'TENSION_PRIMARIA',
  TENSION_SECUNDARIA = 'TENSION_SECUNDARIA',
  SUFIJO_FINAL = 'SUFIJO_FINAL',
  PAIS_CODE = 'PAIS_CODE',
}
